#!/usr/bin/env bash
###############################################################################
# Copyright (c) Intel Corporation - All rights reserved.                      #
# This file is part of the LIBXSMM library.                                   #
#                                                                             #
# For information on the license, see the LICENSE file.                       #
# Further information: https://github.com/hfp/libxsmm/                        #
# SPDX-License-Identifier: BSD-3-Clause                                       #
###############################################################################
# Hans Pabst (Intel Corp.)
###############################################################################

HERE=$(cd "$(dirname $0)"; pwd -P)
if [ "" = "${GIT_DIR}" ]; then
  GIT_DIR=${HERE}/../../.git
fi
LOCKFILE=${GIT_DIR}/.commit

GIT=$(command -v git)
RM=$(command -v rm)

if [ -e "${LOCKFILE}-version" ] && \
   [ "" != "${RM}" ];
then
  # lock file must be deleted *prior* to below commit
  ${RM} "${LOCKFILE}-version"
  # update the version file
  .github/version.sh > version.txt
  # quietly amend the previous commit
  ${GIT} add version.txt
  ${GIT} commit --amend -C HEAD --no-verify >/dev/null
fi

