#!/bin/sh
#############################################################################
# Copyright (c) 2015-2018, Intel Corporation                                #
# All rights reserved.                                                      #
#                                                                           #
# Redistribution and use in source and binary forms, with or without        #
# modification, are permitted provided that the following conditions        #
# are met:                                                                  #
# 1. Redistributions of source code must retain the above copyright         #
#    notice, this list of conditions and the following disclaimer.          #
# 2. Redistributions in binary form must reproduce the above copyright      #
#    notice, this list of conditions and the following disclaimer in the    #
#    documentation and/or other materials provided with the distribution.   #
# 3. Neither the name of the copyright holder nor the names of its          #
#    contributors may be used to endorse or promote products derived        #
#    from this software without specific prior written permission.          #
#                                                                           #
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       #
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         #
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR     #
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT      #
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,    #
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED  #
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR    #
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    #
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      #
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        #
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              #
#############################################################################
# Hans Pabst (Intel Corp.)
#############################################################################

# Appends MSG_TAG to the commit message when no file
# of the change-set matches any of the PATTERNS.
#
HERE=$(cd $(dirname $0); pwd -P)
if [ "" = "${GIT_DIR}" ]; then
  GIT_DIR=${HERE}/../../.git
fi
ROOTDIR=$(cd ${GIT_DIR}/..; pwd -P)
CODEFILE=${ROOTDIR}/.codefile
MSG_TAG="[skip ci]"
MSG_FILE=$1
MSG_KIND=$2

GIT=$(which git 2>/dev/null)

if [ "" != "${GIT}" ] && ! ${GIT} diff --cached --quiet; then # real commit (no amend)
  ECHO=$(which echo 2>/dev/null)
  GREP=$(which grep 2>/dev/null)
  CAT=$(which cat 2>/dev/null)

  if [ "" != "${ECHO}" ] && [ "" != "${GREP}" ] && [ "" != "${CAT}" ] && \
     [ "message" = "${MSG_KIND}" ] && [ "" != "${MSG_FILE}" ] && \
     [ "0" != "$(${GREP} -qs -F "${MSG_TAG}" ${MSG_FILE}; ${ECHO} $?)" ];
  then
    set -o noglob # disable wildcard expansion

    if [ -e ${CODEFILE} ]; then
      PATTERNS="$(${CAT} ${CODEFILE} 2>/dev/null)"
    fi
    PATTERNS+=$(${ECHO} -e "\nMakefile*")

    for FILENAME in $(${GIT} diff --cached --name-only); do
      if [ "" != "$(${ECHO} "${FILENAME}" | ${GREP} -e '^.github/..*' 2>/dev/null)" ]; then
        exit 0
      fi
      if [ "" != "$(${ECHO} "${FILENAME}" | ${GREP} -e 'version.txt' 2>/dev/null)" ]; then
        exit 0
      fi
      BASENAME=$(basename ${FILENAME})
      for PATTERN in ${PATTERNS}; do
        if [[ ${BASENAME} = ${PATTERN} ]]; then # must use double-braces
          exit 0
        fi
      done
    done
    ${ECHO} "${MSG_TAG}" >> ${MSG_FILE}
  fi
fi

