script:
  - make -e ${MAKEJ} && cd samples/deeplearning/rnndriver && make -e ${MAKEJ} &&
   (echo; echo "--- TEST RNN (NCNC-KCCK)"; CHECK=1 ./run_rnncell.sh ncnc_kcck f32 100 0 1 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NCNC-KCCK)"; CHECK=1 ./run_rnncell.sh ncnc_kcck f32 100 0 2 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NCNC-KCCK)"; CHECK=1 ./run_rnncell.sh ncnc_kcck f32 100 0 3 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 0 1 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 3 1 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 0 2 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 3 2 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 0 3 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-KCCK)"; CHECK=1 ./run_rnncell.sh nc_kcck f32 100 3 3 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 0 1 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 3 1 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 0 2 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 3 2 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 0 3 256 32 32 32 ) &&
   (echo; echo "--- TEST RNN (NC-CK)"; CHECK=1 ./run_rnncell.sh nc_ck f32 100 3 3 256 32 32 32 )

  - make -e ${MAKEJ} && cd samples/deeplearning/lstmdriver && make -e ${MAKEJ} &&
   (echo; echo "--- TEST LSTM (NC-CK)"; CHECK=1 ./run_lstmcell.sh nc_ck f32 100 0 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-CK)"; CHECK=1 ./run_lstmcell.sh nc_ck f32 100 3 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-KCCK)"; CHECK=1 ./run_lstmcell.sh nc_kcck f32 100 0 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-KCCK)"; CHECK=1 ./run_lstmcell.sh nc_kcck f32 100 3 256 32 32 32 )

  - make -e ${MAKEJ} && cd samples/deeplearning/lstmdriver && make -e ${MAKEJ} &&
   (echo; echo "--- TEST LSTM (NC-CK/BF16)"; CHECK=1 CHECK_SCALE=0.001 ./run_lstmcell.sh nc_ck bf16 100 0 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-CK/BF16)"; CHECK=1 CHECK_SCALE=0.001 ./run_lstmcell.sh nc_ck bf16 100 3 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-KCCK/BF16)"; CHECK=1 CHECK_SCALE=0.001 ./run_lstmcell.sh nc_kcck bf16 100 0 256 32 32 32 ) &&
   (echo; echo "--- TEST LSTM (NC-KCCK/BF16)"; CHECK=1 CHECK_SCALE=0.001 ./run_lstmcell.sh nc_kcck bf16 100 3 256 32 32 32 )

  - true || (make -e ${MAKEJ} && cd samples/deeplearning/grudriver && make -e ${MAKEJ} &&
   (echo; echo "--- TEST GRU"; CHECK=1 ./grudriver.sh))
