@ECHO OFF

SET MSBUILDDISABLENODEREUSE=1

SET VS=%1
IF "%1" == "" (
  IF NOT "%VS90COMNTOOLS%"  == "" SET VS=vs2008
  IF NOT "%VS100COMNTOOLS%" == "" SET VS=vs2010
  IF NOT "%VS110COMNTOOLS%" == "" SET VS=vs2010
  IF NOT "%VS120COMNTOOLS%" == "" SET VS=vs2013
)

SET ICL_VERSION=%2
IF "%ICL_VERSION%" == "" SET ICL_VERSION=16

:SELECT_ICL_VERSION
IF "%ICL_VERSION%" == "16" SET ICPP_COMPILER=%ICPP_COMPILER16%
IF "%ICL_VERSION%" == "15" SET ICPP_COMPILER=%ICPP_COMPILER15%
IF "%ICL_VERSION%" == "14" SET ICPP_COMPILER=%ICPP_COMPILER14%
IF "%ICL_VERSION%" == "13" SET ICPP_COMPILER=%ICPP_COMPILER13%
IF "%ICL_VERSION%" == "12" SET ICPP_COMPILER=%ICPP_COMPILER12%
IF "%ICPP_COMPILER%" == "" (
  SET/A ICL_VERSION-=1
  GOTO SELECT_ICL_VERSION
)

IF EXIST "%ICPP_COMPILER%bin\compilervars.bat" (
  IF "%PROCESSOR_ARCHITECTURE%" == "x86" (
    CALL "%ICPP_COMPILER%bin\compilervars.bat" ia32 %VS%
  ) ELSE (
    CALL "%ICPP_COMPILER%bin\compilervars.bat" intel64 %VS%
  )
) ELSE (
  SET/A ICL_VERSION-=1
  GOTO SELECT_ICL_VERSION
)

SET MPI_ROOT=%I_MPI_ROOT:-RT=%
