#ifndef LIBXSMM_VERSION_H
#define LIBXSMM_VERSION_H

#define LIBXSMM_CONFIG_VERSION "$VERSION"
#define LIBXSMM_CONFIG_BRANCH "$BRANCH"
#define LIBXSMM_CONFIG_VERSION_MAJOR $MAJOR
#define LIBXSMM_CONFIG_VERSION_MINOR $MINOR
#define LIBXSMM_CONFIG_VERSION_UPDATE $UPDATE
#define LIBXSMM_CONFIG_VERSION_PATCH $PATCH
#define LIBXSMM_CONFIG_BUILD_DATE $DATE

#endif
