#############################################################################
# Copyright (c) 2017-2018, Intel Corporation                                #
# All rights reserved.                                                      #
#                                                                           #
# Redistribution and use in source and binary forms, with or without        #
# modification, are permitted provided that the following conditions        #
# are met:                                                                  #
# 1. Redistributions of source code must retain the above copyright         #
#    notice, this list of conditions and the following disclaimer.          #
# 2. Redistributions in binary form must reproduce the above copyright      #
#    notice, this list of conditions and the following disclaimer in the    #
#    documentation and/or other materials provided with the distribution.   #
# 3. Neither the name of the copyright holder nor the names of its          #
#    contributors may be used to endorse or promote products derived        #
#    from this software without specific prior written permission.          #
#                                                                           #
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       #
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         #
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR     #
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT      #
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,    #
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED  #
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR    #
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    #
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      #
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        #
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              #
#############################################################################
# Sasikanth Avancha, Dhiraj Kalamkar, Alexander Heinecke (Intel Corp.)
#############################################################################

# Graph execution Model (GxM) configuration

CPU_ONLY := 1

# Compiler
CUSTOM_CXX := icpc

USE_OPENCV := 1

# BLAS choice:
# mkl for MKL
#BLAS := openblas
BLAS := mkl

# Use OpenMP
OPENMP := 1

# Architecture
ARCH := avx512_common

# Path to libraries: glog, gflags, protobuf, opencv, lmdb
GXM_LIBRARY_PATH := /path/to/libraries

# Path to libxsmm library for compute
LIBXSMM_PATH := ../../..

BUILD_DIR := build

# Use LMDB; this flag is one always to indicate that the
# only supported db type is LMBD (e.g., not LEVELDB)
LMDB := 1

# Set MLSL flag for multi-node runs; Clear for single-node runs
MLSL := 0

# Set to 1 for debugging -- will compile with -O0 
# turns on debug prints
DEBUG := 0

# Return without compute to measure overhead of framework
RETURN_NC := 0

# Allocate re-usable memory size in BackPropagation
# Useful for MCDRAM-based CPU
BPOPT_ALLOC := 0

#Turn on NUMA Init; Always on
NUMA_ON := 1

#LIBXSMM Options; to time LIBXSMM layers
XSMM_TIMING := 0

# Fine-grained timing; to time all layers
TIME := 0

# Layer Summaries for debugging
STATS := 0

# Dump activations from each layer for debugging
DUMP_ACT := 0

# Dump weights from relevant layers for debugging
DUMP_WT := 0

# Check canary values between tensors to ensure no overflows
CANCHECK := 0

# Flag to check if first K tensor values have gone to
# NaN or Inf due to bugs in code and stop execution
FP32_BU := 1

