#!/bin/sh

VERSIONSCRIPT=${GIT_DIR}/hooks/version.sh
VERSIONFILE=${GIT_DIR}/../version.txt

GIT=$(which git)

# update version file
${VERSIONSCRIPT} > ${VERSIONFILE}

./pre-commit
${GIT} add ${VERSIONFILE}
${GIT} commit --amend -C HEAD --no-verify
