#!/bin/sh

ECHO=$(which echo)
GREP=$(which grep)
GIT=$(which git)

VERSIONFILE=${GIT_DIR}/../version.txt

${ECHO} "merge" > ${VERSIONFILE}
./pre-commit

${GIT} add ${VERSIONFILE}
${GIT} commit --amend -C HEAD --no-verify
