#!/bin/sh

if [[ -e .commit ]] ; then
  MAIN=$(git describe --tags --abbrev=0)
  REVC=$(git describe --tags | cut -d- -f2)
  echo ${MAIN}-$((REVC+1)) > ${GIT_DIR}/../version.txt
  git add ${GIT_DIR}/../version.txt
  git commit --amend -C HEAD --no-verify
  rm .commit
fi
