#!/bin/sh

VERSIONSCRIPT=${GIT_DIR}/hooks/version.sh
VERSIONFILE=${GIT_DIR}/../version.txt
LOCKFILE=${GIT_DIR}/.commit

if [[ -e ${LOCKFILE} ]] ; then
  ECHO=$(which echo)
  GREP=$(which grep)
  GIT=$(which git)
  RM=$(which rm)

  # update version file
  ${VERSIONSCRIPT} > ${VERSIONFILE}

  # lock file must be deleted *prior* to below commit
  ${RM} ${LOCKFILE}

  COMMIT=$(${GIT} diff --name-only | ${GREP} ${VERSIONFILE} ; ${ECHO} $?)
  if [[ "0" != "${COMMIT}" ]] ; then
    ${GIT} add ${VERSIONFILE}
    ${GIT} commit --amend -C HEAD --no-verify
  fi
fi
