#!/bin/sh

ROOTDIR=$(cd ${GIT_DIR}/..; pwd -P 2> /dev/null)
LOCKFILE=${GIT_DIR}/.commit
TOUCH=$(which touch)
ECHO=$(which echo)
GREP=$(which grep)
GIT=$(which git)
SED=$(which sed)
RM=$(which rm)

CODEFILE=${ROOTDIR}/.codefile
BANNED_CHARS="\t"

if [ "" != "${GIT}" ]; then
  if [ "" != "${ECHO}" ] && [ "" != "${SED}" ] && [ "" != "${GREP}" ] && \
     [ "" != "$(${GIT} rev-parse --verify HEAD 2> /dev/null)" ]; \
  then
    if [ -e ${CODEFILE} ]; then
      # transform wildcard-style patterns to regular expressions
      PATTERNS="$(${SED} -e 's/\./\\./g' -e 's/\*/..*/g' -e 's/?/./g' -e 's/$/\$/g' ${CODEFILE} 2> /dev/null)"
    fi
    IFS_BACKUP="${IFS}"
    IFS=""
    while read -r LINE; do
      IFS="${IFS_BACKUP}"
      # determine the filename of the patch snippet
      MATCH=$(${ECHO} "${LINE}" | ${SED} -n "s/^diff --git a\/\(..*\) b..*$/\1/p" 2> /dev/null)
      if [ "" != "${MATCH}" ]; then
        FILENAME=${MATCH}
        LOCATION=""
      elif [ "" != "${FILENAME}" ]; then
        # determine the line number of the change
        MATCH=$(${ECHO} "${LINE}" | ${SED} -n "s/^@@ -..* +\([0-9][0-9]*\),..*$/\1/p" 2> /dev/null)
        if [ "" != "${MATCH}" ]; then LOCATION=":${MATCH}"; fi
        # check against banned characters
        if [ "" != "$(${ECHO} "${LINE}" | ${SED} -n "/^+.*[${BANNED_CHARS}]..*$/p" 2> /dev/null)" ]; then
          # check if problem is with a permitted file type
          for PATTERN in ${PATTERNS}; do
            MATCH=$(${ECHO} "${FILENAME}" | ${GREP} -e "${PATTERN}" 2> /dev/null)
            if [ "" != "${MATCH}" ]; then # print an error message and exit
              >&2 ${ECHO} "Error: ${FILENAME}${LOCATION} contains banned character(s)!"
              exit 1
            fi
          done
        # check against trailing whitespace(s)
        elif [ "" != "$(${ECHO} "${LINE}" | ${SED} -n "/^+.*\s\s*$/p" 2> /dev/null)" ]; then
          # check if problem is with a permitted file type
          for PATTERN in ${PATTERNS}; do
            MATCH=$(${ECHO} "${FILENAME}" | ${GREP} -e "${PATTERN}" 2> /dev/null)
            if [ "" != "${MATCH}" ]; then # print an error message and exit
              >&2 ${ECHO} "Error: ${FILENAME}${LOCATION} has trailing whitespace(s)!"
              #exit 1
              break
            fi
          done
        fi
      fi
      IFS=""
    done \
<< EOD
$(${GIT} diff-index -p -M --cached HEAD)
EOD
    IFS="${IFS_BACKUP}"
  fi

  if [ "" != "${TOUCH}" ] && [ "" != "${GREP}" ] && [ "" != "${RM}" ]; then
    ${GIT} diff --cached --name-status | ${GREP} -q version.txt
    if [ "0" != "$?" ]; then
      # trigger updating the version file
      ${TOUCH} ${LOCKFILE}
    else # cleanup
      ${RM} ${LOCKFILE}
    fi
  fi
fi

