#!/bin/sh
#
# Appends MSG_TAG to the commit message when no file
# of the changeset matches any of the PATTERNS.
#
HERE=$(cd $(dirname $0); pwd -P)
if [ "" = "${GIT_DIR}" ]; then
  GIT_DIR=${HERE}/../.git
fi

ECHO=$(which echo)
GREP=$(which grep)
GIT=$(which git)
CAT=$(which cat)

ROOTDIR=$(cd ${GIT_DIR}/..; pwd -P)
CODEFILE=${ROOTDIR}/.codefile
MSG_TAG="[skip ci]"
MSG_FILE=$1
MSG_KIND=$2

# disable wildcard expansion
set -o noglob

if [ "message" = "${MSG_KIND}" ] && [ "" != "${MSG_FILE}" ] && \
   [ "0" != "$(${GREP} -qs -F "${MSG_TAG}" ${MSG_FILE}; ${ECHO} $?)" ];
then
  if [ -e ${CODEFILE} ]; then
    PATTERNS="$(${CAT} ${CODEFILE} 2> /dev/null)"
  fi
  PATTERNS+=$(${ECHO} -e "\nMakefile*")
  for FILENAME in $(${GIT} diff --cached --name-only); do
    if [[ "" != "$(${ECHO} "${FILENAME}" | ${GREP} -e '^.hooks/..*' 2> /dev/null)" ]]; then
      exit 0
    fi
    BASENAME=$(basename ${FILENAME})
    for PATTERN in ${PATTERNS}; do
      if [[ ${BASENAME} = ${PATTERN} ]]; then
        exit 0
      fi
    done
  done
  ${ECHO} "${MSG_TAG}" >> ${MSG_FILE}
fi

