print "#include<stdio.h>"
print "#include <stdlib.h>"
print "#include <sys/time.h>"
print "#include <micsmm.h>"


print "__declspec( target (mic))"
print "double mytime() {"
print "  timeval a;"
print "  gettimeofday(&a, 0);"
print "  return (double)(a.tv_sec*1000 + a.tv_usec/1000.0);"
print "}"

for n in range(4,30):
    print "__declspec( target (mic))"
    print "void bench_"+str(n)+"(void){"
    print "int length=1;"
    print "double t1,t2;"
    print "double perf1,perf2;"
    print "long iterations = "+str(1000000000/(2*n*n*n))+";"
    print "double* a = new double["+str(n*n)+"];"
    print "double* b = new double["+str(n*n)+"];"
    print "double* c = new double["+str(n*n)+"];"
    print ""
    print "for(int i=0;i<"+str(n*n)+";i++){"
    print "a[i]=((double)i)/((double)"+str(n*n)+");"
    print "b[i]=((double)i)/((double)"+str(n*n)+");"
    print "c[i]=((double)i)/((double)"+str(n*n)+");"
    print "}"
#    print "t1=mytime();"
#    print "for(long n=0;n<iterations;n++){"
#    print "micgemm_1_"+str(n)+"_"+str(n)+"_"+str(n)+"(a,b,c);"
#    print "}"
#    print "t2=mytime();"
#    print "perf1=((double)iterations)*((double)"+str(2*n*n*n)+")/(t2-t1)/((double) 1000)/((double) 1000);"
    print ""
    print "for(int i=0;i<"+str(n*n)+";i++){"
    print "a[i]=((double)i)/((double)"+str(n*n)+");"
    print "b[i]=((double)i)/((double)"+str(n*n)+");"
    print "c[i]=((double)i)/((double)"+str(n*n)+");"
    print "}"
    print "t1=mytime();"
    print "for(long n=0;n<iterations;n++){"
    print "smm_dnn_"+str(n)+"_"+str(n)+"_"+str(n)+"(a,b,c);"
    print "}"
    print "t2=mytime();"
    print "perf2=((double)iterations)*((double)"+str(2*n*n*n)+")/(t2-t1)/((double) 1000)/((double) 1000);"
    print ""
    print "printf(\"%d \\t%f \\t %f \\n\", "+str(n)+", perf1, perf2);"
    print "}"


print "int main(void){"
print "#pragma offload target(mic:0)"
print "{"
print "printf(\"starting benchmark\\n\");"
for n in range(4,30):
    print "bench_"+str(n)+"();"
print "}"
print "}"
